version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: fujihire
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - /Volumes/MiZou/mysql_data:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'  
      - '8025:8025'